version: "3.4"
services:
  postgres:
    image: ${TRINO_GATEWAY_POSTGRES_IMAGE:-postgres}
    environment:
      - PGPORT=5432
      - POSTGRES_PASSWORD=P0stG&es
      - POSTGRES_DB=trino_gateway_db
      - POSTGRES_USER=trino_gateway_db_admin
    ports:
      - "5432:5432"
    healthcheck:
      # Need user and database name to check PostgreSQL server status
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - target: /docker-entrypoint-initdb.d/1-gateway-ha-persistence-postgres.sql
        source: ../gateway-ha/src/main/resources/gateway-ha-persistence-postgres.sql
        type: bind
