apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trino-gateway.fullname" . }}
  labels:
    {{- include "trino-gateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "trino-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "trino-gateway.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "trino-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: consolidate-config
          image: "{{ .Values.initContainer.repository }}:{{ .Values.initContainer.tag }}"
          volumeMounts:
            - name: trino-gateway-configuration-secret
              mountPath: "/etc/secret/config.yaml"
              subPath: "config.yaml"
              readOnly: true
            - name: trino-gateway-configuration
              mountPath: "/etc/gateway/"
              readOnly: false
            {{- with  .Values.dataStoreSecret.key }}
            - name: trino-datastore-secret
              mountPath: "/etc/secret/{{.}}"
              subPath: "{{.}}"
              readOnly: true
            {{- end}}
            {{- with  .Values.backendStateSecret.key }}
            - name: trino-backend-state-secret
              mountPath: "/etc/secret/{{.}}"
              subPath: "{{.}}"
              readOnly: true
            {{- end}}
            {{- with  .Values.authenticationSecret.key }}
            - name: trino-authentication-secret
              mountPath: "/etc/secret/{{.}}"
              subPath: "{{.}}"
              readOnly: true
            {{- end}}
          command:
            - "bash"
            - "-c"
            - "cat /etc/secret/* > /etc/gateway/raw-config.yaml"
        - name: interpolate-env
          image: "{{ .Values.initContainer.repository }}:{{ .Values.initContainer.tag }}"
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12}}
          command:
            {{- toYaml .Values.initContainer.command | nindent 12}}
          volumeMounts:
            - name: trino-gateway-configuration
              mountPath: "/etc/gateway/"
              readOnly: false
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.command | nindent 12}}
          ports:
            - name: request
              containerPort: {{ index .Values "config" "serverConfig" "http-server.http.port" }}
              protocol: TCP
          livenessProbe:
            httpGet:
                path: /trino-gateway
                port: {{ index .Values "config" "serverConfig" "http-server.http.port" }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
                path: /trino-gateway
                port: {{ index .Values "config" "serverConfig" "http-server.http.port" }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: trino-gateway-configuration
              mountPath: "/etc/gateway/"
              readOnly: true
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: trino-gateway-configuration-secret
          secret:
              secretName: trino-gateway-configuration
              optional: false
        - name: trino-gateway-configuration
          emptyDir:
              sizeLimit: 10Mi
        {{- with  .Values.dataStoreSecret.name }}
        - name: trino-datastore-secret
          secret:
              secretName: {{ . }}
              optional: false
        {{- end}}
        {{- with  .Values.backendStateSecret.name }}
        - name: trino-backend-state-secret
          secret:
              secretName: {{ . }}
              optional: false
        {{- end}}
        {{- with  .Values.authenticationSecret.name }}
        - name: trino-authentication-secret
          secret:
              secretName: {{ . }}
              optional: false
        {{- end}}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
