{{ $dataStoreDict :=  dict}}
{{ if .Values.dataStoreSecret.name }}
{{ $dataStoreDict = (index (lookup "v1" "Secret" .Release.Namespace .Values.dataStoreSecret.name).data .Values.dataStoreSecret.key) | b64dec | fromYaml }}
{{ end }}
{{ $backendStateDict := dict }}
{{ if .Values.backendStateSecret.name }}
{{ $backendStateDict = (index (lookup "v1" "Secret" .Release.Namespace .Values.backendStateSecret.name).data .Values.backendStateSecret.key) | b64dec | fromYaml }}
{{ end }}
{{ $authenticationDict := dict }}
{{ if .Values.authenticationSecret.name }}
# {{.Values.authenticationSecret.name }} #
# {{ index (lookup "v1" "Secret" .Release.Namespace .Values.authenticationSecret.name).data .Values.authenticationSecret.key }} #
{{ $authenticationDict = (index (lookup "v1" "Secret" .Release.Namespace .Values.authenticationSecret.name).data .Values.authenticationSecret.key) | b64dec | fromYaml  }}
{{ end }}

apiVersion: v1
kind: Secret
metadata:
    name: trino-gateway-configuration
type: "Opaque"
data:
    config.yaml: "{{toYaml (merge .Values.config $authenticationDict $dataStoreDict $backendStateDict ) | b64enc}}"
