apiVersion: v1
kind: Service
metadata:
  name: {{ include "trino-gateway.fullname" . }}
  labels:
    {{- include "trino-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ index .Values "config" "serverConfig" "http-server.http.port" }}
      protocol: TCP
      name: request
  selector:
    {{- include "trino-gateway.selectorLabels" . | nindent 4 }}
