apiVersion: v1
kind: Service
metadata:
  name: {{ include "trino-gateway.fullname" . }}
  labels:
    {{- include "trino-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.config.requestRouter.port }}
      protocol: TCP
      name: request
    {{- range $index, $connector := $.Values.config.server.applicationConnectors}}
    - port: {{ $connector.port }}
      protocol: TCP
      name: {{print "app-" $index }}
    {{- end }}
    {{- range $index, $connector := $.Values.config.server.adminConnectors}}
    - port: {{ $connector.port }}
      protocol: TCP
      name: {{print "admin-" $index }}
    {{- end }}
  selector:
    {{- include "trino-gateway.selectorLabels" . | nindent 4 }}
