version: "3.4"
services:
  gateway:
    extends:
      file: gateway-compose.yml
      service: gateway
  mysqldb:
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=trinogateway
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3306:3306"
    healthcheck:
      # Need root password to check MySQL server status
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot123"]
      start_period: 20s
      timeout: 5s
      retries: 5
    volumes:
      - target: /etc/mysql/gateway-ha-persistence.sql
        source: ../gateway-ha/src/main/resources/gateway-ha-persistence.sql
        type: bind
      - target: /etc/mysql/add_backends.sql
        source: ./add_backends.sql
        type: bind
  postgres:
    extends:
      file: postgres-backend-compose.yml
      service: postgres
  trino-1:
    image: trinodb/trino:434
    ports:
      - "8081:8080"
  trino-2:
    image: trinodb/trino:434
    ports:
      - "8082:8080"
