name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

defaults:
  run:
    shell: bash --noprofile --norc -Eeuo pipefail {0}

env:
  # Use Maven wrapper from repo with Maven version and other configs
  MAVEN: ./mvnw -B
  MAVEN_FAST_INSTALL: "-B -V -T 1C -DskipTests -Dmaven.source.skip=true -Dair.check.skip-all"

jobs:
  maven-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: 
          - { java-version: 25 }
          - { java-version: 26 }
          - { java-version: 27-ea }
    timeout-minutes: 30
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
      - name: Install required Java distribution
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
          distribution: 'temurin'
      - name: Build with Maven
        run: $MAVEN clean verify

  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
      - name: Install required Java distribution
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'
      - name: Maven Build
        run: $MAVEN install ${MAVEN_FAST_INSTALL}
      - uses: docker/setup-qemu-action@v4
        with:
          platforms: amd64,arm64,ppc64le
      - name: Build and Test Docker Image
        run: docker/build.sh
      - name: Set up Helm
        uses: azure/setup-helm@v5.0.0
        with:
          version: v3.12.1
