name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

env:
  # Use Maven wrapper from repo with Maven version and other configs
  MAVEN: ./mvnw -B

jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/helmpack/chart-testing
    timeout-minutes: 20
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Git safe
        run: git config --system --add safe.directory /__w/trino-gateway/trino-gateway
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull main branch
        run: git fetch origin main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install required Java distribution
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: $MAVEN clean verify
      - name: Install Docker cli for kind
        run: apk add docker-cli
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64,ppc64le
      - name: Build and Test Docker Image
        run: docker/build.sh

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs helm/trino-gateway --target-branch main --all
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get image tag
        run: docker image list

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0

      - name: Run chart-testing (install)
        run: ct install --chart-dirs helm/trino-gateway --target-branch main --all
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

